### ISSUE TITLE
[Morning Session Code Review]

### ISSUE THREAD

**Issue by shah-shuja-dev** [DebbyMiressa/CodingChallenges#2]
# Syed Shuja Hussain
- Hello, I can see that you've done a lot of hard work and built this project with love and passion. And Your Hard work has paid off since your project is one of the most amazing projects I've seen. It is inspiring to me 🥇

![UJr](https://user-images.githubusercontent.com/104627775/181451417-9889e28b-c775-4626-937b-b86645241037.gif)

## Highlights
 - Great Flow of Code 💯 
 - Followed The Best Practices 💯 
 -  No linter Errors 💯 

# Required Changes

- [ ] There's a Horizontal Scroll. Please fix it immediately.
- I've noticed that you've got some elements (specifically your navigation) that are spilling out of their container. I've gone forward and found all of those elements so please kindly see to the issue immediately.
![code Review](https://user-images.githubusercontent.com/104627775/181450138-6918fc10-88b2-4bd5-9e9c-67c27e0b8e14.PNG)

#   Kibirige John 
- Kindly make sure that the logo in the header is the same as the one in the about page as this will show your readers what your site is about and bring out consistency

**Comment by DebbyMiressa** [comment]
Thanks, I will incorporate the changes.
