### ISSUE TITLE
Capstone Code Review

### ISSUE THREAD

**Issue by RiyaBulia12** [DebbyMiressa/CodingChallenges#3]
# Hello @DebbyMiressa   👋 , 

Congratulations! Good job so far!  🎉  I know you've been very diligent and committed to implementing this project, and we, as a team, appreciate the effort you put in! But there are some issues that you still need to work on in this project but you are almost there! 

![so-close](https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

### Suggested Changes ♻️
- How about making dynamic content for innerHTML in `dataLoader()` function rather than restricting it to the number of data currently present in your `Challenge` object? Current code will only work for first 4 data entry coming from your `challenges` object even if the object contains lets say 10 data entry. We suggest you to make following changes in your `dataLoader()` function to make it more efficient and allow it to be more dynamic:
```
function dataLoader() {
// some HTML code should be append to cc
  Object.values(challenges).forEach((val, i) => {
  cc.innerHTML = `
                        <h2>${val.title}</h2>
                        <span><mark>${val.question}</mark></span><br>
                        <label class="fw-bold">Difficulty: </label><span>${val.difficulty}</span><br>
                        <label class="fw-bold">Expected Completion Time: </label><span>${val.expectedtime}</span><br>
                        <button type="button" class="sub oneb btn mt-4">Start Challenge</button>
                        `;
// concat the remaining HTML to cc
  htmlbody.appendChild(cc);
  cc.getBoundingClientRect();
}
```

Cheers and Happy coding!👏👏👏 💻 

Please feel free to reach out or leave any questions or comments on the issue if you find anything unclear

**Comment by DebbyMiressa** [comment]
Thanks for the comment 👍 ; I will integrate the changes on my next commit/push event.
